source "https://rubygems.org"
gemspec

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`
gem "jekyll-github-metadata", ">= 2.15"

gem "jekyll-include-cache", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development

# gem "just-the-docs", "0.9.0" # pinned to the current release
gem "just-the-docs"        # always download the latest release
